export const wordList = [
  { word: "elephant", hint: "A large mammal with a trunk" },
  { word: "banana", hint: "A yellow fruit" },
  {
    word: "mountain",
    hint: "A large natural elevation of the Earth's surface",
  },
  { word: "ocean", hint: "A vast body of salt water" },
  { word: "pyramid", hint: "A triangular structure in Egypt" },
  { word: "chess", hint: "A strategy board game with kings and queens" },
  { word: "tulip", hint: "A type of flower that blooms in spring" },
  { word: "zebra", hint: "An animal with black and white stripes" },
  { word: "guitar", hint: "A stringed musical instrument" },
  { word: "volcano", hint: "A mountain that erupts lava" },
  { word: "rainbow", hint: "A colorful arc in the sky after rain" },
  { word: "castle", hint: "A large fortress or palace" },
  { word: "python", hint: "A type of snake" },
  { word: "coconut", hint: "A tropical fruit with a hard shell" },
  { word: "desert", hint: "A barren area with little rainfall" },
  { word: "forest", hint: "A dense area filled with trees" },
  { word: "eagle", hint: "A bird known for its sharp vision" },
  { word: "river", hint: "A flowing body of water" },
  { word: "sunflower", hint: "A tall flower that faces the sun" },
  { word: "island", hint: "A piece of land surrounded by water" },
  { word: "soccer", hint: "A sport played with a round ball" },
  { word: "penguin", hint: "A flightless bird living in cold regions" },
  { word: "piano", hint: "A musical instrument with keys" },
  { word: "safari", hint: "A wildlife expedition in Africa" },
  { word: "bamboo", hint: "A tall grass eaten by pandas" },
  { word: "tiger", hint: "A large cat with orange and black stripes" },
  { word: "whale", hint: "A large marine mammal" },
  { word: "parrot", hint: "A colorful bird that mimics sounds" },
  { word: "apple", hint: "A red or green fruit" },
  { word: "sphinx", hint: "A mythical creature with a lion's body" },
  { word: "moon", hint: "Earth's natural satellite" },
  { word: "dolphin", hint: "A friendly aquatic mammal" },
  { word: "cactus", hint: "A spiny plant found in deserts" },
  { word: "honey", hint: "A sweet substance made by bees" },
  { word: "igloo", hint: "A dome-shaped snow house" },
  { word: "camel", hint: "An animal known as the 'ship of the desert'" },
  { word: "diamond", hint: "A precious gemstone" },
  { word: "swan", hint: "A graceful white bird" },
  { word: "carnival", hint: "A festive event with parades and games" },
  { word: "pepper", hint: "A spicy vegetable or seasoning" },
  { word: "kangaroo", hint: "A marsupial found in Australia" },
  { word: "violin", hint: "A stringed musical instrument played with a bow" },
  { word: "planet", hint: "A celestial body orbiting a star" },
  { word: "orchid", hint: "A delicate and exotic flower" },
  { word: "sandwich", hint: "Two slices of bread with filling" },
  { word: "galaxy", hint: "A system of stars, dust, and gas" },
  { word: "lighthouse", hint: "A tower with a light to guide ships" },
  { word: "dragon", hint: "A mythical creature that breathes fire" },
  { word: "avocado", hint: "A green fruit with a creamy texture" },
  { word: "castle", hint: "A medieval fortress" },
  { word: "rainforest", hint: "A dense tropical forest" },
  { word: "pyramid", hint: "A triangular monument in Egypt" },
  { word: "waterfall", hint: "A cascade of water flowing down rocks" },
  { word: "robot", hint: "A machine designed to perform tasks" },
  { word: "butterfly", hint: "An insect with colorful wings" },
  { word: "jungle", hint: "A dense forest in tropical regions" },
  { word: "balloon", hint: "A lightweight inflatable object" },
  { word: "iceberg", hint: "A large piece of floating ice" },
  { word: "treasure", hint: "A hidden collection of valuable items" },
  { word: "spider", hint: "An arachnid that weaves webs" },
  { word: "pirate", hint: "A person who robs ships" },
  { word: "peacock", hint: "A bird with vibrant tail feathers" },
  { word: "strawberry", hint: "A small red fruit with seeds outside" },
  { word: "bridge", hint: "A structure spanning a gap" },
  { word: "umbrella", hint: "A device used for protection from rain" },
  { word: "snowflake", hint: "A single ice crystal" },
  { word: "penguin", hint: "A bird that lives in Antarctica" },
  { word: "candle", hint: "A source of light made of wax" },
  { word: "cloud", hint: "A mass of water droplets in the sky" },
  { word: "butter", hint: "A dairy product made from cream" },
  { word: "rocket", hint: "A vehicle for space travel" },
  { word: "mango", hint: "A sweet tropical fruit" },
  { word: "firefly", hint: "An insect that glows in the dark" },
  { word: "harbor", hint: "A place where ships dock" },
  { word: "blossom", hint: "A flower, especially in spring" },
  { word: "lantern", hint: "A portable light source" },
  { word: "mirror", hint: "A surface reflecting images" },
  { word: "shadow", hint: "A dark shape cast by an object" },
  { word: "volcano", hint: "A mountain that erupts lava" },
  { word: "horizon", hint: "The line where sky meets earth" },
  { word: "key", hint: "A tool to unlock doors" },
  { word: "garden", hint: "A cultivated area for plants" },
  { word: "crystal", hint: "A solid material with a regular pattern" },
  { word: "flamingo", hint: "A pink bird with long legs" },
  { word: "tornado", hint: "A powerful rotating windstorm" },
  { word: "ballerina", hint: "A female ballet dancer" },
  { word: "pumpkin", hint: "A round orange vegetable" },
];
